### ISSUE TITLE
Beautify style and script tag content

### ISSUE THREAD

**Issue by wmhilton** [GitScrum/posthtml-beautify#163]
How do you feel about running the content of `<style></style>` tags through stylefmt and the contents of `<script></script>` tags through eslint?

**Comment by GitScrum** [comment]
Hi, i think this is unnecessary for this plugin. For this already there are plugins:
- style - see [add format and sortig style](https://github.com/GitScrum/posthtml-beautify/issues/3)
- script - use [eslint-plugin-html](https://www.npmjs.com/package/eslint-plugin-html)

**Comment by wmhilton** [comment]
Ah! I didn't know those plugins. Is there already some high level code cleaning application that uses all three of these? Am I missing the forest for the trees?

**Comment by GitScrum** [comment]
I have not yet met, now the emphasis is placed on the micromodule because Combined are difficult to support and not flexible.

**Comment by wmhilton** [comment]
That makes sense. Every use case is different.
