### ISSUE TITLE
[feat]: Customize/turn off formatting rules

### ISSUE THREAD

**Issue by andreyvolokitin** [GitScrum/posthtml-beautify#216]
Is it possible currently? In the docs I see [3 rules](https://github.com/GitScrum/posthtml-beautify#rules) available for customization. For now, I need to turn off vertical indentation (it honestly looks somewhat confusing, because it makes empty lines in unexpected places). All in all, I would prefer to just use horizontal indentation because that's what gets broken while using ```posthtml-include``` and such. Everything else I handle myself and would prefer to keep unchanged

**Comment by andreyvolokitin** [comment]
Removed [last ```getIndent(0)```](https://github.com/GitScrum/posthtml-beautify/blob/master/src/index.js#L118), that removed all vertical indentation. So I'm afraid that currently, it is not possible to preserve original vertical indentation because it gets destroyed in the first place?

**Comment by GitScrum** [comment]
Yes, all initial formatting is deleted. A new one is created. Show me how you would like and I'll think about how best to do it.

**Comment by andreyvolokitin** [comment]
My problem is that when using ```posthtml-include``` or ```posthtml-extend``` the HTML which gets outputted by these plugins is lacking proper horizontal formatting, like so:
```html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
    <h2>Extend:</h2>

    <div class="posthtml-include-output">
  <div class="content">
    Read
  </div>
  <footer>
    footer
  </footer>
</div>
    </body>
</html>
```
so I want to just fix horizontal indentation of HTML outputted by these plugins.

I guess this is probably even worth a separate plugin like ```posthtml-fix-output``` as the difference with the goals of ```posthtml-beautify``` is huge... It would be possible though if every tiny rule of ```posthtml-beautify``` would be pluggable, so only desired rules/transformations could be turned on. There are already an array of transformations which can be tweaked, but transformations themselves seems like lacking granular control

**Comment by andreyvolokitin** [comment]
Probably better use something like this after webpack build: https://github.com/beautify-web/js-beautify#css--html, it appears like a big task to adapt ```posthtml-beautify``` for my use case

**Comment by GitScrum** [comment]
`beautify-web/js-beautify` most likely it will also remove all your current indentation and create your own based on the options.

> it appears like a big task to adapt posthtml-beautify for my use case

you will be easier to configure `posthtml-cli` - I will make a new pool requester in your repository `posthtml-beautify-test` where I will show that this is easy

**Comment by andreyvolokitin** [comment]
Thanks, would appreciate it. ```js-beautify``` indeed reformats everything (which is somewhat undesirable), but it can be tuned, i.e. I can keep almost all original vertical indentation preserved there (https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-html.js#L53). Though it yet cannot understand cases when collapsed whitespace between tags needs to stay preserved, instead it adds a new line between them, which is critical because it can break HTML layout which depends on presence or absence of whitespace

**Comment by GitScrum** [comment]
@andreyvolokitin Hi, So far I've added an option for management `blankLines`, also created a task to save the current structure #220. 

And I also remember about the example that promised, now `posthtml-cli` he had difficulties and I solve them

**Comment by andreyvolokitin** [comment]
Have I understood it correctly: ```blankLines``` option controls the addition of *new* newlines, but not removing existing newlines? To preserve existing newlines and overall structure there is #220, correct?

**Comment by GitScrum** [comment]
@andreyvolokitin remove all `blankLines`

*input.html*
```html
<div>

<div>test</test>

</div>
```

*output.html*
```html
<div>
  <div>test</test>
</div>
```

#220 to save the current structure with formatted indents.

**Comment by andreyvolokitin** [comment]
OKay, so the process is this:
- currently by design```posthtml-beautify``` removing all blank lines
- then some blank lines are added due to this feature: https://i.imgur.com/Sf4ZrSP.png
- but you can disable this feature with ```blankLines: false```, and in that case no such blank lines are added
- the final result of this is the example you provided: _all_ blank lines are removed, but _none_ are added.

I think this is what you meant

**Comment by GitScrum** [comment]
@andreyvolokitin 🎉🎉🎉  try.

> you will be easier to configure posthtml-cli - I will make a new pool requester in your repository posthtml-beautify-test where I will show that this is easy

https://github.com/andreyvolokitin/posthtml-beautify-test/pull/2

**Comment by andreyvolokitin** [comment]
Thanks! Will check it out
