### ISSUE TITLE
[feat]: How to turn off blank line

### ISSUE THREAD

**Issue by VladShcherbin** [GitScrum/posthtml-beautify#217]
Hey, I want to use beautify, but don't want blank lines between blocks. Here is a simple example:

```html
<body>
  <p>hey</p>
  <p>ho</p>
  <p>hey</p>
</body>
```

Compiles to:

```html
<body>
  <p>hey</p>

  <p>ho</p>

  <p>hey</p>
</body>
```

In this example I want compiled version to be the same as original. I tried options like `beautify({ rules: { eol: '\n' } })`, but it doesn't work.

Is it somehow possible to do?

**Comment by GitScrum** [comment]
@VladShcherbin Thank you for this feature. We will wait for you from new bugs / offers / pool of requests :)

Please do not forget to put the star projects that you like))

**Comment by VladShcherbin** [comment]
@GitScrum very nice, thank you!
