### ISSUE TITLE
Support sync mode

### ISSUE THREAD

**Issue by sjelfull** [GitScrum/posthtml-beautify#70]
When I try to use posthtml-beautify with posthtml running in sync mode, I get this error: 

`Error: Can’t process contents in sync mode because of async plugin:`

**Comment by GitScrum** [comment]
Thanks for you reply, sorry it took so long to answer. I implemented support for synchronicity. Now you only need to update posthtml-beautify. You just need to specify in the options `sync: true` `posthtml` the processor or plugin `posthtml-beautify` or both.

example with options sync true the `posthtml`
```js
posthtml([beautify()]).process(html, {sync: true})
```

example with options sync true the `posthtml-beautify`
```js
posthtml([beautify({sync: true})]).process(html)
```

example with options sync true the `posthtml-beautify` and `posthtml`
```js
posthtml([beautify({sync: true})]).process(html, {sync: true})
```

enjoy, have a good day.

**Comment by sjelfull** [comment]
Thanks, that's great! I'll test it tomorrow.
